server:
  port: 8090

spring:
  application:
    name: redbird
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/redbird?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: RedBird_2020
  resources:
    static-locations: classpath:/static

  #配置redis
  redis:
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.redbird.pojo #设置pojo在mybaits中的别名
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: dao.

## thymeleaf静态资源配置
## 默认路径
#  thymeleaf:
#   prefix: classpath:/templates/
#   sufffix: .html
#   model: HTML5
#   encoding: UTF-8
#   content-type: text/html
#   cache: false

#-----------------------------------实验---------------------------------------
pagehelper:
  auto-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true
